# -*- coding: utf-8 -*-
"""
research_v3.py — a FULL RE-SEARCH under the v3 objective. Not a rescoring.

WHY A RE-SEARCH IS NEEDED
`FINAL_ranked4.csv` was generated by `rank4_branch` under the OLD objective: it pruned with a
bound involving V and kept only the top 1,200 rows per branch. Rescoring those rows under a
new objective cannot find a timetable the old search discarded. R233's reversal to "defer
Language" was a rescoring, so it is a hypothesis until the space is searched again.

THE v3 OBJECTIVE (DESIGN_V3, with R233's measured K)

    score(x) = week(x) + Σ year_pen(x) + chapel(x) + difficulty(x)   − K(deferred)

  · **No V, no crowding.** `continuation.py` is not imported. `crowding.json` — still convex
    where every measured curve is concave (R228) — has no influence on anything here.
  · K depends only on WHICH requirement is deferred, never on the Fall 2026 timetable, so it
    is a per-branch constant and the within-branch search is unaffected by it. That is why the
    search can be run once and the K scenarios applied afterwards without re-searching.
  · Feasibility Φ (does the remainder admit a legal 6-semester plan) is likewise a per-branch
    property; all six branches were verified feasible, so it cannot reorder anything either.

THE BOUND — sound, and far tighter than what it replaces
`rank4_branch` pruned with the constant 276.0 because R219 showed two attempted replacements
were unsound. The sound one:

    fast_score(final) = week_value(final) + Σ day_pen(final)
                     ≤ week_value(partial)        [day_pen ≤ 0, exhaustively verified;
                                                   week_value non-increasing in occupancy]

and every remaining elective's year-penalty is ≤ 0, so nothing else can push the total up.
Per R219 this is verified by RE-DERIVING A KNOWN RANKING, not by argument: each branch must
reach at least the best value found by rescoring the old candidate set.

⚠️ ASSUMPTIONS KEPT VISIBLE (not baked in)
  · n = 4 — the receiving-semester load. 신촌 at n=5 (167 masks × 6 free choices) exceeded
    every search budget tried; 국제 reaches n=5. Both are reported where available.
  · The filler baseline is ≥3 scheduled hours. Verified appropriate: EVERY identifiable
    remaining ledger item of Iden's is a 3-hour course, and only ~10% of 3-credit sections
    catalogue-wide run in 2 hours. 17 of 38 units (DM, FREE) have no course identity at all.
  · Per-YEAR K values are carried through separately and never medianed into one number.
"""
import json, os, sys, csv, time, heapq, itertools, collections, statistics

import rank as RK
import rank2 as R2, difficulty as DIFF
R2.LANG = set(DIFF.LANG_ALL)
import rank3
from rank2 import fast_score, week_value, YEAR_PEN, eff_year

HERE = os.path.dirname(os.path.abspath(__file__))
CHAPEL_BONUS, CHAPEL_DEFER = 10.0, -4.2
# ⛔ R111 — N_ACADEMIC = 6 IS IDEN'S DECISION, NOT A CAP. Do not "discover" the 7-course
# branch and do not widen the search to 3 open slots. Spring 2026 GPA >= 3.75 makes 21
# credits legal (초과수강); he was asked 6 vs 7 on 2026-08-06 and chose 6, and restated it
# on 2026-08-16. R111's own words: "do not re-raise it as an oversight."
# CR_HI = 21.0 is VESTIGIAL — it is the 초과수강 ceiling and is unreachable while
# N_ACADEMIC = 6 with 3-credit sections (all 67,345 ranked rows are exactly 18 credits).
# It is left in place only so the window is not silently wrong if N_ACADEMIC ever moves.
# CR_LO = 17.0 likewise excludes the legal 5-course/15-credit branch, by the same choice.
# ⭐ R193: 18 credits is also 18/18 = 1.00 on tie-break rung ⓗ (직전학기이수학점/수강가능학점),
# which sets his mileage rank in EVERY future round. The load has a permanent consequence.
N_ACADEMIC = 6
CR_LO, CR_HI = 17.0, 21.0
TOPN = int(os.environ.get("RV_TOPN", 20000))   # R269 — 3000 truncated below the argmax of total (score + unit_cost - K)
MAX_FREE = int(os.environ.get('MAX_FREE', 99))   # free electives allowed THIS semester
BRANCHES = ['-', 'MR', 'WCiv', 'LHP', 'SciRD', 'Lang']
STATE = os.path.join(HERE, f"_v3_parts_f{os.environ.get('MAX_FREE','99')}")
os.makedirs(STATE, exist_ok=True)

# best value reachable per branch by RESCORING the old candidate set (R233).
# The re-search must reach at least these, or the bound is unsound (R219).
KNOWN_FLOOR = {'-': 10.315, 'MR': 31.194, 'WCiv': 23.940,
               'LHP': 18.890, 'SciRD': 25.940, 'Lang': 33.390}


def build():
    P, sig, sigs, SIGCODES, code = rank3.build()
    import fm_fix; fm_fix.apply(P)   # R239: fm per SEGMENT, not per course mode
    import eligibility; eligibility.apply(P)   # R240: drop 폐강 + hard exclusions
    LANGP = [s for s in P['OPEN'] if code(s) in R2.LANG]
    ELEC = [s for s in P['OPEN'] if code(s) not in R2.LANG]
    REQ = {'MR': P['MR'], 'WCiv': P['WCiv'], 'LHP': P['LHP'],
           'SciRD': P['SciRD'], 'Lang': LANGP}
    return P, REQ, ELEC, code


def run_branch(name, P, REQ, ELEC, code):
    names = list(REQ)
    defer = () if name == '-' else tuple(name.split('+'))
    taken = [n for n in names if n not in defer]
    nslots = N_ACADEMIC - len(taken)

    # electives collapsed on (nominal, presence, fixed, year-pen, credits, LEDGER ITEM).
    # ⭐ the item must be in the signature: two sections at the same hours are NOT
    # interchangeable if one advances a Major Elective and the other burns a free elective.
    import rank4 as _R4
    import prof as PROF
    # ⭐ g[3] is now the section's FULL per-section bonus: year-penalty PLUS professor.
    # The professor term must be in the KEY, or two sections at the same hours collapse and
    # the better-taught one becomes unreachable — `esig[g][0]` is the representative.
    esig = collections.defaultdict(list)
    for s in ELEC:
        esig[(s['tm'], s['pm'], s['fm'],
              YEAR_PEN(eff_year(s, code)) + PROF.bonus(s['c']), s['cr'],
              _R4.item_of_section(s, code))].append(s)
    ekeys = sorted(esig, key=lambda g: -g[3])
    ECODES = {g: {code(s) for s in esig[g]} for g in ekeys}
    # ⛔ SOUNDNESS. The branch ceiling below assumes remaining picks cannot RAISE the score.
    # That held while g[3] was a year penalty (always <= 0). A professor bonus can be
    # positive, so the ceiling must credit the best still-available bonus per empty slot,
    # or the search prunes branches that would have won.
    PBMAX = max([g[3] for g in ekeys] + [0.0])

    heap, cnt, best = [], [0], [-1e9]

    def push(sc, key):
        if sc > best[0]:
            best[0] = sc
        if len(heap) < TOPN or sc > heap[0][0]:
            it = (sc, cnt[0], key); cnt[0] += 1
            heapq.heappush(heap, it) if len(heap) < TOPN else heapq.heapreplace(heap, it)

    t0 = time.time()
    for ch in P['Chapel'] + [None]:
        ch_t = ch['tm'] if ch else 0
        ch_p = ch['pm'] if ch else 0
        ch_f = ch['fm'] if ch else 0
        ch_c = CHAPEL_BONUS if ch else CHAPEL_DEFER
        for combo in itertools.product(*[REQ[n] for n in taken]):
            tm, pm, fm, ok = ch_t, ch_p, ch_f, True
            for s in combo:
                if tm & s['tm']:
                    ok = False; break
                tm |= s['tm']; pm |= s['pm']; fm |= s['fm']
            if not ok:
                continue
            base_codes = {code(s) for s in combo}
            if len(base_codes) < len(combo):
                continue
            cr = sum(s['cr'] for s in combo)
            pen = sum(YEAR_PEN(eff_year(s, code)) for s in combo)
            dif = -DIFF.D_LANG * DIFF.GPA_GATE_MULT * sum(DIFF.steps(code(s)) for s in combo)
            # professor bonus on the FIXED part of the timetable (requirements + chapel)
            pb = sum(PROF.bonus(s['c']) for s in combo) + (PROF.bonus(ch['c']) if ch else 0.0)
            cand = [g for g in ekeys if not (tm & g[0]) and (ECODES[g] - base_codes)]

            def rec(i, k, t, p, f, c, b, used, chosen, nfree):
                # ⭐ SOUND CEILING (replaces rank4_branch's constant 276.0)
                # `k * PBMAX` credits the best professor bonus still reachable in each empty
                # slot — without it a positive prof term makes this bound unsound.
                if week_value(p, f)[0] + b + k * PBMAX + pen + dif + pb + ch_c <= best[0]:
                    return
                if k == 0:
                    if not (CR_LO <= c <= CR_HI):
                        return
                    sc = fast_score(t, p, f)[0] + b + pen + dif + pb + ch_c
                    push(sc, (tuple(s['c'] for s in combo), ch['c'] if ch else None,
                              tuple(esig[g][0]['c'] for g in chosen),
                              tuple(g[5] for g in chosen)))
                    return
                if len(cand) - i < k:
                    return
                for j in range(i, len(cand)):
                    g = cand[j]
                    if t & g[0]:
                        continue
                    if not (ECODES[g] - used):
                        continue
                    if c + g[4] + 3.0 * (k - 1) > CR_HI:
                        continue
                    nf = nfree + (1 if g[5] == 'FREE' else 0)
                    if nf > MAX_FREE:            # ⭐ the free-elective budget, as a constraint
                        continue
                    rec(j + 1, k - 1, t | g[0], p | g[1], f | g[2], c + g[4],
                        b + g[3], used | ECODES[g], chosen + (g,), nf)

            rec(0, nslots, tm, pm, fm, cr, 0.0, base_codes, (), 0)

    out = sorted(heap, key=lambda x: -x[0])
    rec_out = [dict(score=round(sc, 3), requirements=list(k[0]), chapel=k[1] or '-',
                    electives=list(k[2]), items=list(k[3])) for sc, _n, k in out]
    # ⚠️ the scoring constants are STAMPED into the part file. STATE is keyed only on
    # MAX_FREE, so without this a `D_LANG=999 python research_v3.py Lang` prints "cached"
    # and recomputes nothing — which is exactly why neither D_LANG nor GPA_GATE_MULT had
    # ever actually been swept (audited 2026-08-16). See sweep_holes.py.
    json.dump({'branch': name, 'rows': rec_out,
               'consts': {'D_LANG': DIFF.D_LANG, 'GPA_GATE_MULT': DIFF.GPA_GATE_MULT,
                          'MAX_FREE': MAX_FREE,
                          # R250 again: the 0-vs-max prof comparison is exactly a run that
                          # differs ONLY in these, so they MUST be in the cache stamp.
                          'PROF_W': PROF.PROF_W, 'PROF_UNRATED': PROF.UNRATED,
                          'PROF_RATED': len(PROF.ratings()),
                          # R269: TOPN determines WHICH rows survive, so it is an input.
                          'TOPN': TOPN}},
              open(os.path.join(STATE, f'part_{name}.json'), 'w', encoding='utf-8'),
              ensure_ascii=False)
    # ⚠️ the floor is an UNCONSTRAINED lower bound from rescoring the old candidate set.
    # It is only a valid check when this run is also unconstrained: MAX_FREE=0 legitimately
    # scores below it, and eligibility filtering (R240) can also remove the row that set it.
    fl = KNOWN_FLOOR.get(name) if MAX_FREE >= 2 else None
    flag = ''
    if fl is not None:
        if out[0][0] < fl - 1e-3:
            flag = f"  ⛔ BELOW the rescored floor {fl:.3f} — THE BOUND IS UNSOUND"
        elif out[0][0] > fl + 1e-3:
            flag = f"  ⭐ ABOVE the rescored floor {fl:.3f} by {out[0][0]-fl:.3f} — the old search HAD missed rows"
        else:
            flag = f"  ✅ reproduces the rescored floor {fl:.3f} exactly"
    print(f"branch {name:6s}: {len(rec_out)} kept, best {out[0][0]:8.3f}, "
          f"{time.time()-t0:.0f}s{flag}", flush=True)


def cache_is_valid(path):
    """A cached branch may only be reused if it was scored with the CURRENT constants.

    STATE is keyed on MAX_FREE alone. Before the constants were stamped into the file
    (2026-08-16) a cached part was reused no matter what D_LANG or GPA_GATE_MULT were set
    to, so every sweep over them silently returned the baseline. Missing `consts` means the
    file predates the stamp and cannot be trusted.
    """
    if not (os.path.exists(path) and os.path.getsize(path)):
        return False, 'absent'
    try:
        c = (json.load(open(path, encoding='utf-8')) or {}).get('consts')
    except Exception:
        return False, 'unreadable'
    if not c:
        return False, 'pre-stamp (no consts recorded)'
    import prof as PROF
    want = {'D_LANG': DIFF.D_LANG, 'GPA_GATE_MULT': DIFF.GPA_GATE_MULT, 'MAX_FREE': MAX_FREE,
            'PROF_W': PROF.PROF_W, 'PROF_UNRATED': PROF.UNRATED,
            'PROF_RATED': float(len(PROF.ratings())), 'TOPN': float(TOPN)}
    diff = {k: (c.get(k), v) for k, v in want.items() if abs((c.get(k) or 0) - v) > 1e-9}
    return (not diff), ('stale: ' + ', '.join(f'{k} {a}->{b}' for k, (a, b) in diff.items())
                        if diff else 'current')


if __name__ == '__main__':
    P, REQ, ELEC, code = build()
    for b in (sys.argv[1:] or BRANCHES):
        ok, why = cache_is_valid(os.path.join(STATE, f'part_{b}.json'))
        if ok:
            print(f"branch {b}: cached"); continue
        if why not in ('absent',):
            print(f"branch {b}: RECOMPUTING — {why}")
        run_branch(b, P, REQ, ELEC, code)
