"""Core timetable-optimizer primitives introduced during the Stage 4 rebuild."""

from .catalog import (
    CatalogIssue,
    CatalogSnapshot,
    IssueCode,
    ListingObservation,
    ListingStatus,
    ObservationStatus,
    PhysicalSectionRecord,
    PhysicalStatus,
    ReconciliationKind,
    SectionObservation,
    SourceRef,
    ingest_catalog,
    load_catalog_files,
)
from .sections import (
    DAYS,
    DeliveryKind,
    NoListedSchedule,
    ParsedSchedule,
    Schedule,
    ScheduleSegment,
    Section,
    SectionParseError,
    SegmentAlignmentError,
    UnresolvedSchedule,
    classify_room_segment,
    mask_from_blocks,
    parse_schedule,
    section_from_raw,
    segment_blocks,
)

__all__ = [
    "CatalogIssue",
    "CatalogSnapshot",
    "DAYS",
    "DeliveryKind",
    "IssueCode",
    "ListingObservation",
    "ListingStatus",
    "NoListedSchedule",
    "ObservationStatus",
    "ParsedSchedule",
    "PhysicalSectionRecord",
    "PhysicalStatus",
    "ReconciliationKind",
    "Schedule",
    "ScheduleSegment",
    "Section",
    "SectionObservation",
    "SectionParseError",
    "SegmentAlignmentError",
    "SourceRef",
    "UnresolvedSchedule",
    "classify_room_segment",
    "ingest_catalog",
    "load_catalog_files",
    "mask_from_blocks",
    "parse_schedule",
    "section_from_raw",
    "segment_blocks",
]
